### PR TITLE
FAQ Page for the site

### PR DESCRIPTION
**Pull request by Suyash-Srivastava**
Is it good or any additions needed?

### CODE REVIEW

**Review by punidramesh — CHANGES_REQUESTED** [review]
Add necessary spacings and formatting

**Comment by punidramesh** [comment]
Refer to : https://xd.adobe.com/view/5a295662-b64a-42b2-b7d3-09af067132b8-0f7a/screen/9cd103b7-1264-4048-a037-02d540ca1978/specs/

**Comment by Suyash-Srivastava** [comment]
Sir only spacing to the left margin or any changes in text also

**Comment by punidramesh** [comment]
Text formatting (bold & italics) and decrease the top margin for the heading

**Comment by Suyash-Srivastava** [comment]
Sir I have updated the file

**Comment by punidramesh** [comment]
Fix the margins in mobile view

Expected : 
image

Got : 
image

**Pull request closed without merging**
